---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(extrafont)
```

```{r}
(df_sdg_targets <- read_csv('.//data/sdg_targets.csv'))
```

```{r}
excl_groups <- c('Afr - Fragile Health', 'Afr - Middling Health', 'Afr - HIV Burden', 'Afr - Imp Health',
                 'Africa', 'AFP Central Africa', 'AFP Southern Africa', 'AFP Western Africa', 
                 'AFP Northern Africa', 'AFP East/Horn Africa')
```

```{r}
(df_master <- readxl::read_xlsx('.//data/IFs_results_02apr2019.xlsx', sheet='update_10apr2019') %>% 
   filter(scenario == '00CP_adj_ADB'))

(df_master_UHC <- readxl::read_xlsx('.//data/IFs_results_02apr2019.xlsx', sheet='update_10apr2019') %>% 
   filter(scenario == '01UHC_africa'))

```

```{r}
(df_master_2 <- df_master %>% select(1:5, `2015`, `2020`, `2030`, `2063`))
```

```{r}
(df_maternal_2 <- df_master_2 %>% 
  filter(variable == 'MATMORTRATIO') %>% 
  select(variable, country, `2030`) %>% 
  bind_rows(., df_sdg_targets %>% filter(variable == 'MATMORTRATIO')) %>% 
  mutate(africa = 1))
```

```{r}
(df_maternal_3 <- df_maternal_2 %>% 
  mutate(scale_2030 = scale(`2030`)) %>% 
  mutate(distance = ifelse(`2030` <= 70, 0, min(scale_2030) - scale_2030)) %>% 
  arrange(distance))

df_maternal_2 %>% 
  mutate(mean_ = mean(`2030`),
         stdev_ = sd(`2030`)) %>% 
  slice(1) %>% 
  select(variable, mean_, stdev_)
```

```{r}
df_master_2 %>% 
  mutate(variable = ifelse(unit %in% c('TrafficAcc', 'AIDS', 'Malaria', 'NonCommun'), 
                           as.character(unit), 
                           as.character(variable))) 
```


```{r}
(df_neonatal_2 <- df_master_2 %>% 
   filter(variable == 'NEONATMOR') %>% 
  select(variable, country, `2030`) %>% 
  bind_rows(., df_sdg_targets %>% filter(variable == 'NEONATMOR')) %>% 
   mutate(africa = 1))
```

```{r}
(df_neonatal_3 <- df_neonatal_2 %>% 
  mutate(scale_2030 = scale(`2030`)) %>% 
  mutate(distance = ifelse(`2030` <= 12, 0, min(scale_2030) - scale_2030)) %>% 
  arrange(distance))
```


```{r}
(df_u5mr_2 <- df_master_2 %>% 
   filter(variable == 'CHILDDTHR') %>% 
  select(variable, country, `2030`) %>% 
  bind_rows(., df_sdg_targets %>% filter(variable == 'CHILDDTHR')) %>% 
   mutate(africa = 1))
```

```{r}
(df_u5mr_3 <- df_u5mr_2 %>% 
  mutate(scale_2030 = scale(`2030`)) %>% 
  mutate(distance = ifelse(`2030` <= 25, 0, min(scale_2030) - scale_2030)) %>% 
  arrange(distance))
```



```{r}
(df_ncd_2 <- df_master_2 %>% 
  filter(unit == 'NonCommun') %>% 
  select(unit, country, `2015`, `2030`) %>% 
   mutate(ratio_2030 = `2030` / `2015`) %>% 
   select(-c(`2015`, `2030`)) %>% 
  rename('variable' = 'unit',
         '2030' = 'ratio_2030') %>% 
  bind_rows(., df_sdg_targets %>% filter(variable == 'NonCommun')))
```

```{r}
(df_ncd_3 <- df_ncd_2 %>% 
  mutate(scale_2030 = scale(`2030`)) %>% 
  mutate(distance = ifelse(`2030` <= 2/3, 0, min(scale_2030) - scale_2030)) %>% 
  arrange(distance))
```

```{r}
(df_traff_2 <- df_master_2 %>% 
  filter(variable == 'DeathRate',
         unit == 'TrafficAcc') %>% 
  mutate(ratio_2020 = `2020` / `2015`) %>% 
  select(unit, country, ratio_2020) %>% 
  rename('variable' = 'unit',
         '2020' = 'ratio_2020') %>% 
   bind_rows(., df_sdg_targets %>% filter(variable == 'TrafficAcc') %>% rename('2020' = '2030')))
```

```{r}
(df_traff_3 <- df_traff_2 %>% 
  mutate(scale_2020 = scale(`2020`)) %>% 
  mutate(distance = ifelse(`2020` <= .5, 0, min(scale_2020) - scale_2020)) %>% 
  arrange(distance))
```


```{r}
(df_sdg_targets_2 <- read_csv('.//data/sdg_targets_2.csv'))
```


```{r}
(df_sdg_targets_3 <- df_sdg_targets %>% 
  mutate(targ_dist_2030 = `2030`) %>% 
  select(-`2030`))
```

```{r}
(df_sdg_targets_traff <- df_sdg_targets %>% 
  filter(variable == 'TrafficAcc') %>% 
  rename('targ_dist_2020' = '2030'))
```


```{r}
(df_scaled_dist_results <- df_master_2 %>% 
  filter(variable %in% c('MATMORTRATIO', 'NEONATMOR', 'CHILDDTHR') | 
         unit %in% c('AIDS', 'Malaria')) %>% 
  mutate(variable = ifelse(unit %in% c('AIDS', 'Malaria'), as.character(unit), as.character(variable))) %>% 
  select(variable, country, `2030`) %>% 
  bind_rows(., 
            df_sdg_targets_2 %>% 
              filter(!variable %in%  c('NonCommun', 'TrafficAcc'))) %>% 
  spread(variable, `2030`) %>% 
  mutate_at(vars(AIDS:NEONATMOR), funs(scale(.))))
```

```{r}
target_df <- data.frame('TARGET', 2/3, .5)

names(target_df) <- c('country', 'NonCommun', 'TrafficAcc')

target_df
```


```{r}
target_df_2 <- data.frame('TARGET', .001, .001)

names(target_df_2) <- c('country', 'AIDS', 'Malaria')

```


```{r}
(df_scaled_dist_results_rel_targets <- df_master_2 %>% 
  filter(unit %in% c('TrafficAcc', 'NonCommun')) %>% 
  select(unit, country, `2015`, `2020`, `2030`) %>% 
  rename('variable' = 'unit') %>% 
  mutate(ratio_ = ifelse(variable == 'TrafficAcc', `2020` / `2015`, `2030` / `2015`)) %>% 
  select(-c(3:5)) %>% 
  spread(variable, ratio_) %>% 
  bind_rows(., target_df) %>% 
  mutate_at(vars(NonCommun:TrafficAcc), funs(scale(.))))
```

```{r pardee.theme.minimal, include=TRUE}
pardee.theme.minimal <- theme(
  plot.title = element_text(color="black", face="plain", size=10, hjust=0), 
  plot.subtitle = element_text(color="black", size=15, hjust=0), 
  axis.title = element_text(color="black", face="plain", size=14), 
  axis.text.y = element_text(size=13), 
  axis.text.x = element_text(angle = 90, hjust = 1, size=16), 
  plot.caption = element_text(color="black", size=13), 
  panel.background =  element_blank(), 
  #panel.grid.major = element_line(colour = "grey90", size = 0.5),
  #panel.grid.minor = element_line(colour = "grey93", size = 0.5),
  panel.border = element_blank(), 
  #panel.border = element_rect(colour = "black", size = 0.5, fill=NA, linetype = 1),
  legend.title=element_blank(), 
  legend.text = element_text(color="black", size=14, hjust=0),
  legend.spacing.x = unit(.5, 'cm'), 
  legend.position = 'bottom',
  strip.text = element_text(color="black", face="plain", size=16),
  strip.background = element_rect(fill = "white"))
```


```{r}
df_scaled_dist_results
```


```{r fig.height=6.2}
(demo_plot <- df_scaled_dist_results %>% 
  ggplot(.) + 
  geom_density(data=. %>% filter(country != 'TARGET'),
               aes(MATMORTRATIO)) + 
  geom_vline(data=. %>% filter(country == 'TARGET'),
             aes(xintercept = MATMORTRATIO), color='black') + 
  #geom_vline(data=. %>% filter(country != 'TARGET'),
   #          aes(xintercept = mean(MATMORTRATIO)), linetype = 'longdash') + 
  geom_vline(data=. %>% filter(country == 'Benin'),
             aes(xintercept = MATMORTRATIO), linetype = 'longdash') +  
  labs(y='% of countries\n',
       x='Standardized values in 2030') + 
  ggtitle("Maternal mortality, Benin's distance value is .97 (-.12 less -1.09)") + 
  annotate("text", x=-.6, y=.12, label = 'Target (-1.09)', color='green3', size=5.5) + 
  annotate("text", x=.35, y=.12, label = 'Benin (-.12)', color='black', size=5.5) + 
  scale_y_continuous(labels = 'percent') + 
  pardee.theme.minimal + 
   theme(plot.title = element_text(size = 12)))
```

```{r}
#ggsave("distance_explained.png", plot = demo_plot, height = 6, width = 10, family="Avenir-Book", device='png')
```

```{r}
#df_scaled_dist_results %>% 
 # left_join(x=.,
  #          y=df_scaled_dist_results_rel_targets,
   #         by='country') %>% 
  #write.csv(., 'scaled_abs_targets_10apr2019_v2.csv')
```



```{r}
(cntry_order <- df_scaled_dist_results %>% 
  left_join(x=.,
            y=df_scaled_dist_results_rel_targets,
            by='country') %>% 
  gather(var, val, 2:8) %>% 
  group_by(country) %>% 
  summarise(avg_val = mean(val)) %>% 
  arrange(avg_val) %>% 
  filter(country != 'TARGET'))
```

```{r}
(cntry_order <- factor(cntry_order$country))
```

```{r}
(dist_plot_df <- df_scaled_dist_results %>% 
  filter(country != 'TARGET') %>% 
  left_join(x=.,
            y=df_scaled_dist_results_rel_targets,
            by='country') %>% 
  #left_join(x=.,
   #         y=cntry_order,
    #        by='country') %>% 
  #arrange(-avg_val) %>% 
  gather(var, val, 2:8))
```

```{r}
#Turn your 'treatment' column into a character vector
dist_plot_df$country <- as.character(dist_plot_df$country)
#Then turn it back into a factor with the levels in the correct order
dist_plot_df$country <- as.factor(dist_plot_df$country)

dist_plot_df$country <- factor(dist_plot_df$country, levels=cntry_order)

```


```{r}
(df_target_scaled_vals <- df_scaled_dist_results %>% 
  filter(country == 'TARGET') %>% 
  left_join(x=.,
            y=df_scaled_dist_results_rel_targets %>% filter(country == 'TARGET'),
            by='country') %>% 
  gather(var, target, 2:8) %>% 
  select(2:3))
```


```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
targ_cols <- c('AIDS' = "#E69F00", 
               'CHILDDTHR' = "#56B4E9",
               'Malaria' = "#009E73",
               'MATMORTRATIO' = "#F0E442",
               'NEONATMOR' = "#0072B2",
               'NonCommun' = "#D55E00",
               'TrafficAcc' = "#CC79A7")
```

```{r}
(dist_plot_df_2 <- dist_plot_df %>% 
  left_join(x=.,
            y=df_target_scaled_vals,
            by='var'))
```

```{r}
(test_2 <- dist_plot_df_2 %>% 
  mutate(achieve = ifelse(val <= target, 1, 0)) %>% 
  filter(achieve == 0) %>% 
  group_by(country) %>% 
  summarise(min_val = min(val),
            max_val = max(val)))
```



```{r fig.width=10, fig.height=35}
dist_plot_df_2 %>% 
  mutate(achieve = ifelse(val <= target, 1, 0)) %>% 
  filter(achieve == 0) %>% 
  ggplot(.,
         aes(x=val, 
             y=country)) + 
  geom_point(aes(color=var), 
             #height=.25, width=0,
             alpha=.5, size=8) + 
  geom_segment(data=test_2,
               aes(x=min_val, xend=max_val, yend=country),
               color='gray60', size=1) + 
  labs(x='',
       y='') + 
  pardee.theme.minimal + 
  theme(legend.position = 'top') + 
  scale_color_manual(values = targ_cols,
                     labels = c('MATMORTRATIO' = 'Maternal Mortality',
                               'NEONATMOR' = 'Neonatal Mortality',
                               'CHILDDTHR' = '< 5 Mortality',
                               'NonCommun' = 'NCDs',
                               'TrafficAcc' = 'Traffic Mortality')) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_x_continuous(position = 'top')
```
