---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(extrafont)
library(scales)
```

```{r message=FALSE}
df <- read_csv('.//data/ADB_results_20june2019.csv')
```

```{r}
(df <- df %>% 
  separate(variable, into=c('variable', 'scenario_num'), sep = '\\[') %>% 
  select(c(1, 3:5, 7, `2015`, `2020`, `2030`)))
```

```{r}
(df <- df %>% 
  mutate(variable = ifelse(variable == 'DeathRate', dim1, 
                    ifelse(variable == 'HIV Incidence SDG Indicator', 'AIDS', 
                           variable)),
         target_year_value = ifelse(variable == 'TrafficAcc', `2020` / `2015`, 
                             ifelse(variable == 'NonCommun', `2030` / `2015`, 
                                    `2030`))))
```

```{r}
(df_sdg_targets <- read_csv('.//data/sdg_targets.csv'))
```

```{r}
(df_sdg_targets_2 <- read_csv('.//data/sdg_targets_2.csv'))
```


**Note: this is not including all variables, yet. Working now on absolute targets, and not yet with death rates.**

```{r}
(df <- df %>% 
  left_join(x=.,
            y=df_sdg_targets_2,
            by='variable') %>% 
  rename('target' = '2030.y',
         '2030' = '2030.x',
         'country' = 'country.x') %>% 
  select(-country.y))
```


```{r}
(df <- df %>% 
  mutate(dist_perc = ifelse(target_year_value <= target, 
                            0, 
                            round((target_year_value - target) / target * 100, 3))))
```

```{r}
adb_groups <- c('Africa', 'Afr - CDs Clust', 'Afr - Double Burden', 'Afr - NCDs & HIV', 'Afr - NCDs Clust')
```

```{r}
(adb_clusters <- kmeans_viz_data %>% 
  select(country, clust_name))
```

```{r}
(df <- df %>% 
  left_join(x=.,
            y=adb_clusters,
            by='country'))
```


```{r}
(df_summary_dist <- df %>% 
  group_by(country, scenario) %>% 
  summarise(avg_dist_perc = mean(dist_perc, na.rm = TRUE)) %>% 
  arrange(-avg_dist_perc))
```

```{r fig.width=10, fig.height=4}
df %>% 
  mutate(achieve = ifelse(dist_perc == 0, 'Achieve', 'Not Achieve')) %>% 
  filter(achieve != 'Achieve',
         country %in% adb_groups,
         scenario == '00iCurrentPa',
         !variable %in% c('AIDS', 'Malaria')) %>% 
  ggplot(.,
         aes(x=dist_perc / 100, 
             y=country)) + 
  geom_point(aes(color=variable), 
             #height=.25, width=0,
             alpha=.5, size=8) + 
  #geom_segment(data=test_2,
   #            aes(x=min_val, xend=max_val, yend=country),
    #           color='gray60', size=1) + 
  labs(x='Percent distance from achievement\n',
       y='') + 
  pardee.theme.minimal + 
  theme(legend.position = 'top') + 
  scale_color_manual(values = targ_cols,
                     labels = c('MATMORTRATIO' = 'Maternal Mortality',
                               'NEONATMOR' = 'Neonatal Mortality',
                               'CHILDDTHR' = '< 5 Mortality',
                               'NonCommun' = 'NCDs',
                               'TrafficAcc' = 'Traffic Mortality')) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_x_continuous(position = 'top',
                     labels = percent)
```


```{r fig.width=8, fig.height=15}
df %>% 
  mutate(achieve = ifelse(dist_perc == 0, 'Achieve', 'Not Achieve')) %>% 
  filter(achieve != 'Achieve',
         !is.na(clust_name),
         scenario == '00iCurrentPa') %>% 
  ggplot(.,
         aes(x=dist_perc / 100, 
             y=country)) + 
  geom_point(aes(color=variable), 
             #height=.25, width=0,
             alpha=.5, size=8) + 
  facet_wrap(~clust_name, ncol = 1, scales = 'free_y') + 
  #geom_segment(data=test_2,
   #            aes(x=min_val, xend=max_val, yend=country),
    #           color='gray60', size=1) + 
  labs(x='Percent distance from achievement\n',
       y='') + 
  pardee.theme.minimal + 
  theme(legend.position = 'top') + 
  scale_color_manual(values = targ_cols,
                     labels = c('MATMORTRATIO' = 'Maternal Mortality',
                               'NEONATMOR' = 'Neonatal Mortality',
                               'CHILDDTHR' = '< 5 Mortality',
                               'NonCommun' = 'NCDs',
                               'TrafficAcc' = 'Traffic Mortality')) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_x_continuous(position = 'top',
                     labels = percent)
```





# Visualize

```{r fig.width=10, fig.height=35}
dist_plot_df_2 %>% 
  mutate(achieve = ifelse(val <= target, 1, 0)) %>% 
  filter(achieve == 0) %>% 
  ggplot(.,
         aes(x=val, 
             y=country)) + 
  geom_point(aes(color=var), 
             #height=.25, width=0,
             alpha=.5, size=8) + 
  geom_segment(data=test_2,
               aes(x=min_val, xend=max_val, yend=country),
               color='gray60', size=1) + 
  labs(x='',
       y='') + 
  pardee.theme.minimal + 
  theme(legend.position = 'top') + 
  scale_color_manual(values = targ_cols,
                     labels = c('MATMORTRATIO' = 'Maternal Mortality',
                               'NEONATMOR' = 'Neonatal Mortality',
                               'CHILDDTHR' = '< 5 Mortality',
                               'NonCommun' = 'NCDs',
                               'TrafficAcc' = 'Traffic Mortality')) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_x_continuous(position = 'top')
```


